import { Toaster } from 'react-hot-toast';
import '.././../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>

      {children}
      <Toaster />
    </section>

  );
}
